# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f5ad095ad5a4f3e2fa9b4e7476672f84b9dd4d3c6665029c1f9c75fc545e9be8eb53bf0cf1929425cc4ab6c48392055b21f415f50ee798f115c09b8df6c314f

test:
  secret_key_base: 39bd63a16b05dd9f62647a92497ec3d7e85f8de2ed2bf9440fc7a90bd1c28eba8de2a82f9e20e499bff41c08909a9f0bc58db9ce0e9265d00b5775997686cf49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
